apiVersion: v1
kind: Namespace
metadata:
  name: giraldo-paul-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: giraldo-paul-config
  namespace: giraldo-paul-namespace
data:
  paulgiraldo.log: |
    El curso es muy interesando, estoy aprendiendo mucho
    creo sera de mucha ayuda en mi desarrollo profesional

---
apiVersion: v1
kind: Secret
metadata:
  name: giraldo-paul-secret
  namespace: giraldo-paul-namespace
type: Opaque
data:
  paterno: Z2lyYWxkbw==
  materno: cGFsYWNpb3M=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giraldo-paul-deployment
  namespace: giraldo-paul-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-hello
  template:
    metadata:
      labels:
        app: pg-hello
    spec:
      containers:
      - name: pg-hello-container
        image: paulgiraldo/caso02:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: log-volume
          mountPath: "/app"
        env:
          - name: CLAVE
            valueFrom:
              secretKeyRef:
                name: giraldo-paul-secret
                key: clave
      volumes:
        - name: log-volume
          configMap:
            name: giraldo-paul-config
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: giraldo-paul-service
  namespace: giraldo-paul-namespace
spec:
  selector:
    app: pg-hello
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
  type: LoadBalancer
